# Generated by Django 2.2.5 on 2019-10-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
