# Generated by Django 2.2.5 on 2019-10-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0003_auto_20191007_1213'),
        ('clientel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='plat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plat_reserver', to='resto.Plat'),
            preserve_default=False,
        ),
    ]
