# Generated by Django 2.2.5 on 2019-10-09 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientel', '0002_reservation_plat'),
        ('clientel', '0002_reservation_message'),
    ]

    operations = [
    ]
