# Generated by Django 2.2.5 on 2019-10-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientel', '0004_remove_reservation_plat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
