# Generated by Django 2.2.5 on 2019-10-06 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='active',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='presentation',
            old_name='active',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='reserveconfig',
            old_name='active',
            new_name='status',
        ),
    ]
