# Generated by Django 2.2.5 on 2019-10-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20191006_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghour',
            name='end_hour',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='start_hour',
            field=models.TextField(max_length=50),
        ),
    ]
