# Generated by Django 2.2.5 on 2019-10-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_auto_20191007_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghour',
            name='end_hour',
            field=models.TimeField(max_length=50),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='start_hour',
            field=models.TimeField(max_length=50),
        ),
    ]
