# Generated by Django 2.2.5 on 2019-10-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_auto_20191007_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='image_about/'),
        ),
    ]
