# Generated by Django 2.2.5 on 2019-10-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_auto_20191007_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='image_about'),
        ),
    ]
