# Generated by Django 2.2.5 on 2019-10-08 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnel',
            options={'verbose_name': 'Personnel', 'verbose_name_plural': 'Personnels'},
        ),
    ]
