# Generated by Django 2.2.5 on 2019-10-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0002_auto_20191008_1734'),
        ('resto', '0003_auto_20191007_1213'),
    ]

    operations = [
    ]
