# Generated by Django 2.2.5 on 2019-10-09 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0004_merge_20191009_1234'),
        ('resto', '0002_auto_20191007_1307'),
    ]

    operations = [
    ]
